---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - keti-metric.keti-exascale.keti-metric
  resources:
  - gpus
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keti-metric.keti-exascale.keti-metric
  resources:
  - gpus/finalizers
  verbs:
  - update
- apiGroups:
  - keti-metric.keti-exascale.keti-metric
  resources:
  - gpus/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - keti-metric.keti-exascale.keti-metric
  resources:
  - nodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keti-metric.keti-exascale.keti-metric
  resources:
  - nodes/finalizers
  verbs:
  - update
- apiGroups:
  - keti-metric.keti-exascale.keti-metric
  resources:
  - nodes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - keti-metric.keti-exascale.keti-metric
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keti-metric.keti-exascale.keti-metric
  resources:
  - pods/finalizers
  verbs:
  - update
- apiGroups:
  - keti-metric.keti-exascale.keti-metric
  resources:
  - pods/status
  verbs:
  - get
  - patch
  - update
